name: calendar
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter: 
  uses-material-design: true
 
  assets:
    - assets/icons/
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
